---
- name: Check if commit is set
  debug: 
    msg: "Deploy commit hash {{ blog_commit_hash }}"

- name: Install docker pip package
  pip:
    name: docker

- name: Add restricted user 
  user:
    name: dockeruser
    group: docker

- name: Pull image
  docker_image:
    name: "{{ blog_image_name  }}"
    tag: "{{ blog_commit_hash }}"
    source: pull

- name: Update systemd unit
  template:
    src: "systemd.j2" 
    dest: "/etc/systemd/system/blog.service"
  notify: Restart blog systemd unit

- name: Update nginx config
  template:
    src: "nginx.conf.j2" 
    dest: "/etc/nginx/conf.d/blog.conf"
  notify: Test nginx config

- name: Start and enable the service
  systemd:
    name: 'blog'
    state: started
    enabled: yes

