name: push

on:
  push:
    branches:
      - '**'

env:
  IMAGE_NAME: strangeman/pelican-blog
  BUILDKIT_INLINE_CACHE: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build App
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cached
          cache-to: type=inline
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Test
        run: |
          echo "I didn't write tests, so this step does nothing"

      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cached
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
